server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port:  27017
      database: testDatabase
      authentication-database: admin
      username: test-user
      password: test-user-password